Tensorflow is an open-source ML framework developed by Google. This is well suited for development of Neural Network.
High Level APIs like Keras for simplicity of making High Level Dense ANN Model.
Hardware Acceleration with GPU and TPU.

In [2]:
import tensorflow as tf
import numpy as np

#### 1. Scalar (Rank 0 Tensor)

In [4]:
# Scalar value with Rank = 0
const_1 = tf.constant(10)
print(const_1)

tf.Tensor(10, shape=(), dtype=int32)


#### tf.constant(value, dtype = , shape = , name = 'Const')

#### 2. Vector ( Rank 1 Tensor)

In [6]:
# dtype = int8, int16, int32, int64
const_2 = tf.constant([10, 20, 30, 40, 50, 60, 70], dtype = 'int16')

In [7]:
print(const_2)

tf.Tensor([10 20 30 40 50 60 70], shape=(7,), dtype=int16)


#### 3. Matrices (Rank 2 Tensor)

In [12]:
const_3=tf.constant([[11,12,13,14,15,16],
                     [21,22,23,24,25,26],
                     [31,32,33,34,35,36]],dtype='int16')

print(const_3)

tf.Tensor(
[[11 12 13 14 15 16]
 [21 22 23 24 25 26]
 [31 32 33 34 35 36]], shape=(3, 6), dtype=int16)


In [13]:
print(const_3.numpy())

[[11 12 13 14 15 16]
 [21 22 23 24 25 26]
 [31 32 33 34 35 36]]


In [15]:
const_3.shape

TensorShape([3, 6])

#### 4. Tensor (>=3 Rank)

In [18]:
const_4 = tf.constant([[[11, 12, 13, 14, 15, 16],
                       [21, 22, 23, 24, 25, 26],
                       [31, 32, 33, 34, 35, 36]],
                      
                      [[11, 12, 13, 14, 15, 16],
                       [21, 22, 23, 24, 25, 26],
                       [31, 32, 33, 34, 35, 36]],
                      
                      [[11, 12, 13, 14, 15, 16],
                       [21, 22, 23, 24, 25, 26],
                       [31, 32, 33, 34, 35, 36]]], dtype = 'int16')
print(const_4)

tf.Tensor(
[[[11 12 13 14 15 16]
  [21 22 23 24 25 26]
  [31 32 33 34 35 36]]

 [[11 12 13 14 15 16]
  [21 22 23 24 25 26]
  [31 32 33 34 35 36]]

 [[11 12 13 14 15 16]
  [21 22 23 24 25 26]
  [31 32 33 34 35 36]]], shape=(3, 3, 6), dtype=int16)


In [19]:
const_4.shape

TensorShape([3, 3, 6])

#### Tensor using numpy

In [23]:
mat_1 = np.random.randint(0, 255, size = (10,3))
mat_2 = np.random.randint(0, 255, size = (10,3))
mat_3 = np.random.randint(0, 255, size = (10,3))

In [24]:
const_5=tf.constant([mat_1,mat_2,mat_3])

In [25]:
const_5

<tf.Tensor: shape=(3, 10, 3), dtype=int32, numpy=
array([[[ 17,  23,  16],
        [ 27, 184, 185],
        [ 81, 217, 181],
        [184, 202,  23],
        [230, 155, 100],
        [164,  15, 213],
        [107, 230,  63],
        [ 71, 138, 190],
        [ 32,   0, 245],
        [102,  24,  61]],

       [[  3, 110, 171],
        [114, 214, 214],
        [ 72, 192, 243],
        [ 75, 178, 117],
        [  7,  32,  34],
        [216, 175, 102],
        [116,  59, 226],
        [148, 115, 228],
        [206,  51,  21],
        [122, 204, 240]],

       [[180,   0, 166],
        [ 60,  40, 112],
        [229, 181,  67],
        [ 11, 234, 210],
        [176,  59,  53],
        [ 71,  84, 133],
        [ 52,  46, 253],
        [213, 213, 208],
        [ 46, 154,  74],
        [221,  30,  19]]], dtype=int32)>

#### Mutable Tensor - tf.variable() , as tf.constant is immutable in python

In [26]:
matrix_1 = np.random.randint(0, 255, size = (3,6))
var_1=tf.Variable(matrix_1)

In [27]:
var_1

<tf.Variable 'Variable:0' shape=(3, 6) dtype=int64, numpy=
array([[ 99, 252, 246, 146, 133, 148],
       [233, 180, 174, 229,  18,  91],
       [ 52,  92, 103, 135, 244, 125]])>

In [29]:
var_1[2,2].assign(100)

<tf.Variable 'UnreadVariable' shape=(3, 6) dtype=int64, numpy=
array([[ 99, 252, 246, 146, 133, 148],
       [233, 180, 174, 229,  18,  91],
       [ 52,  92, 100, 135, 244, 125]])>

In [32]:
new_row=np.array([29,37,57,93,82,139]).reshape(1,6)
new_row_tf = tf.Variable(new_row)

In [33]:
tf.concat([var_1, new_row_tf], axis = 0)

<tf.Tensor: shape=(4, 6), dtype=int64, numpy=
array([[ 99, 252, 246, 146, 133, 148],
       [233, 180, 174, 229,  18,  91],
       [ 52,  92, 100, 135, 244, 125],
       [ 29,  37,  57,  93,  82, 139]])>

In [34]:
var_1

<tf.Variable 'Variable:0' shape=(3, 6) dtype=int64, numpy=
array([[ 99, 252, 246, 146, 133, 148],
       [233, 180, 174, 229,  18,  91],
       [ 52,  92, 100, 135, 244, 125]])>

In [36]:
new_col = np.array([ 124, 244, 130]).reshape(3,1)
new_col_tf = tf.Variable(new_col)


In [37]:
tf.concat([var_1, new_col_tf], axis = 1)

<tf.Tensor: shape=(3, 7), dtype=int64, numpy=
array([[ 99, 252, 246, 146, 133, 148, 124],
       [233, 180, 174, 229,  18,  91, 244],
       [ 52,  92, 100, 135, 244, 125, 130]])>

#### 5. Mathematical operation in tensor

In [3]:
X = tf.constant([[2],
                 [3],
                 [4],
                 [5],
                 [6],
                 [3]], dtype = 'float16')

In [4]:
Weights = tf.Variable([[0.1],
                       [0.3],
                       [0.17],
                       [0.5],
                       [0.6],
                       [1.3]], dtype = 'float16')

In [5]:
WT = tf.transpose(Weights)

In [6]:
# Y = WT * X + Bias
Y = tf.matmul(WT, X)
Y

<tf.Tensor: shape=(1, 1), dtype=float16, numpy=array([[11.78]], dtype=float16)>

In [8]:
bias=tf.constant(2.4, dtype='float16')

In [9]:
tf.matmul(WT, X) + bias

<tf.Tensor: shape=(1, 1), dtype=float16, numpy=array([[14.18]], dtype=float16)>

#### Dense Neural Network / Feed Forward Network / Fully connected Layer - Multi Classification

In [13]:
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.models import Sequential 
from tensorflow.keras.optimizers import Adam, Adagrad

In [14]:
def build_model():
    model = Sequential()
    # input shape = num of features
    model.add(Input(shape = (8,)))
    # Input Layer - I
    # units = number of neurons in each layer, activation function = 'relu'
    model.add(Dense(units = 32, activation = 'relu'))
    # Hidden Layer - I
    model.add(Dense(units = 64, activation = 'relu'))
    # Hidden Layer - II
    model.add(Dense(units = 128, activation = 'relu'))
    # Ouput Layer
    model.add(Dense(units = 3, activation = 'softmax'))
    model.compile(loss = 'categorical_crossentropy', optimizer = 'Adam', metrics = ['accuracy'])
    return model

In [15]:
model = build_model()

In [16]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 32)                  │             288 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 64)                  │           2,112 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 128)                 │           8,320 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 3)                   │             387 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 11,107 (43.39 KB)

 Trainable params: 11,107 (43.39 KB)

 Non-trainable params: 0 (0.00 B)